# Generated by Django 5.0.4 on 2026-01-29 23:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankrolladjustment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('4000000'))]),
        ),
        migrations.AlterField(
            model_name='tournamentinput',
            name='cashed_for',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4000000)]),
        ),
    ]
